name: Bug Report
description: Create a new ticket for a bug
labels: ['bug']
assignees:
  - jtreeves
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions below before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation, especially the [README](https://github.com/jtreeves/wordiest)
        - Ensure the bug has not already been [reported](https://github.com/jtreeves/wordiest/labels/bug)
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
