name: Feature Request
description: Create a new ticket for a feature request
labels: ['enhancement']
assignees:
  - jtreeves
body:
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions below before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation, especially the [README](https://github.com/jtreeves/wordiest)
        - Ensure the feature has not already been [requested](https://github.com/jtreeves/wordiest/labels/enhancement)
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What other solutions have you attempted?
    validations:
      required: false
