basePath: /api
definitions:
  model.Response:
    properties:
      data: {}
    type: object
  model.Word:
    properties:
      id:
        type: integer
      length:
        type: integer
      letter:
        type: string
      value:
        type: string
    type: object
host: localhost:1234
info:
  contact: {}
  description: A simple API for receiving word data
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Wordiest API
  version: "1.0"
paths:
  /word:
    get:
      consumes:
      - application/json
      description: Returns a random word from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Word'
              type: object
      summary: Get single word
      tags:
      - word
swagger: "2.0"
