name: Post-Deploy Checks
on:
  workflow_run:
    workflows: ['Deploy on Merge']
    types:
      - completed
permissions:
  issues: write
  contents: read
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          architecture: x64
      - name: Fix Flutter version
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
          flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run integration tests
        run: flutter test test/integration_tests
  issue-creation:
    runs-on: ubuntu-latest
    needs: integration-tests
    if: failure()
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Failure occurred when running integration tests
          body: One or more integration tests failed after the latest deployment.
          labels: tests
          assignees: jtreeves
